<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WinFormsToAvalonia.Core\WinFormsToAvalonia.Core.csproj" />
    <ProjectReference Include="..\WinFormsToAvalonia.FallbackControls\WinFormsToAvalonia.FallbackControls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
