<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>NestedFormApp</RootNamespace>
    <AssemblyName>NestedFormApp</AssemblyName>
  </PropertyGroup>

</Project>
