<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SenderAndDragApp</RootNamespace>
    <AssemblyName>SenderAndDragApp</AssemblyName>
  </PropertyGroup>

</Project>
