<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Shell</RootNamespace>
    <AssemblyName>Shell</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Widgets\Widgets.csproj" />
  </ItemGroup>
</Project>
